<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'fournisseur' => [[], ['_controller' => 'App\\Controller\\FournisseurController::index'], [], [['text', '/fournisseur']], [], []],
    'affichef' => [[], ['_controller' => 'App\\Controller\\FournisseurController::affiche'], [], [['text', '/afficher_fourni']], [], []],
    'ajouterf' => [[], ['_controller' => 'App\\Controller\\FournisseurController::ajouterf'], [], [['text', '/ajouter_fourni']], [], []],
    'modiferf' => [['id'], ['_controller' => 'App\\Controller\\FournisseurController::modifierf'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/modifierf']], [], []],
    'supprimerf' => [['id'], ['_controller' => 'App\\Controller\\FournisseurController::supprimerf'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/fournisseur/supprimerf']], [], []],
    'produit' => [[], ['_controller' => 'App\\Controller\\ProduitController::index'], [], [['text', '/produit']], [], []],
    'affichep' => [[], ['_controller' => 'App\\Controller\\ProduitController::affichep'], [], [['text', '/afficher_prod']], [], []],
    'affichep2' => [[], ['_controller' => 'App\\Controller\\ProduitController::affichep2'], [], [['text', '/afficher_prod2']], [], []],
    'ajouterp' => [[], ['_controller' => 'App\\Controller\\ProduitController::ajouterp'], [], [['text', '/ajouter_prod']], [], []],
    'modifierp' => [['idProd'], ['_controller' => 'App\\Controller\\ProduitController::modifierp'], [], [['variable', '/', '[^/]++', 'idProd'], ['text', '/modifierp']], [], []],
    'supprimerp' => [['idProd'], ['_controller' => 'App\\Controller\\ProduitController::supprimerp'], [], [['variable', '/', '[^/]++', 'idProd'], ['text', '/produit/supprimerp']], [], []],
];
